In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as stat

df=pd.read_csv("/content/drive/MyDrive/Dataset Data Mining /Dataset/lab_label.txt")

#show Data set
print(df)
df.describe()


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
       District  Size  Population      Speciality
0         Dhaka  1432     2250000  Administrative
1       Gazipur   879      567984        Industry
2   Narayanganj   576       53426        Industry
3       Rajbari   897       65899     Agriculture
4    Chittagong  1234     1345566        Industry
5   Cox's Bazer   456       46567         Tourist
6     Bandarban   345       67579         Tourist
7       Khustia   432       57798        Business
8          Feni   543       67890     Agriculture
9       Comilla   564       77898         Tourist
10      Barisal   577       89750     Agriculture
11     Faridpur   567       77650     Agriculture
12      Rangpur   575       78966     Agriculture
13      Chadpur   876       67789         Tourist


In [ ]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
df["New District"]=le.fit_transform(df["District"])
# Print the updated DataFrame
print(df)

       District  Size  Population      Speciality  New District
0         Dhaka  1432     2250000  Administrative             6
1       Gazipur   879      567984        Industry             9
2   Narayanganj   576       53426        Industry            11
3       Rajbari   897       65899     Agriculture            12
4    Chittagong  1234     1345566        Industry             3
5   Cox's Bazer   456       46567         Tourist             5
6     Bandarban   345       67579         Tourist             0
7       Khustia   432       57798        Business            10
8          Feni   543       67890     Agriculture             8
9       Comilla   564       77898         Tourist             4
10      Barisal   577       89750     Agriculture             1
11     Faridpur   567       77650     Agriculture             7
12      Rangpur   575       78966     Agriculture            13
13      Chadpur   876       67789         Tourist             2


In [ ]:
from sklearn.preprocessing import OneHotEncoder

oh =OneHotEncoder(sparse_output=False,
                    handle_unknown='error',
                    drop='first')

dfn =oh.fit_transform(df[["District"]])

# Print the updated DataFrame
print(dfn)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
ohendf=pd.DataFrame(dfn)
print(ohendf)

     0    1    2    3    4    5    6    7    8    9    10   11   12
0   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
4   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
11  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
13  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 

In [ ]:
df= df.join(ohendf)
print(df)

       District  Size  Population      Speciality  New District  Bandarban  \
0         Dhaka  1432     2250000  Administrative             6        0.0   
1       Gazipur   879      567984        Industry             9        0.0   
2   Narayanganj   576       53426        Industry            11        0.0   
3       Rajbari   897       65899     Agriculture            12        0.0   
4    Chittagong  1234     1345566        Industry             3        0.0   
5   Cox's Bazer   456       46567         Tourist             5        0.0   
6     Bandarban   345       67579         Tourist             0        1.0   
7       Khustia   432       57798        Business            10        0.0   
8          Feni   543       67890     Agriculture             8        0.0   
9       Comilla   564       77898         Tourist             4        0.0   
10      Barisal   577       89750     Agriculture             1        0.0   
11     Faridpur   567       77650     Agriculture             7 

In [ ]:
dff=pd.read_csv("/content/drive/MyDrive/Dataset Data Mining /Dataset/heart.csv")
dff

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [ ]:
dff.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
x = dff.drop('target', axis=1)
x


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [ ]:
y = dff['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [ ]:
dff.corr()

age       sex        cp  trestbps      chol       fbs  \
age       1.000000 -0.098447 -0.068653  0.279351  0.213678  0.121308   
sex      -0.098447  1.000000 -0.049353 -0.056769 -0.197912  0.045032   
cp       -0.068653 -0.049353  1.000000  0.047608 -0.076904  0.094444   
trestbps  0.279351 -0.056769  0.047608  1.000000  0.123174  0.177531   
chol      0.213678 -0.197912 -0.076904  0.123174  1.000000  0.013294   
fbs       0.121308  0.045032  0.094444  0.177531  0.013294  1.000000   
restecg  -0.116211 -0.058196  0.044421 -0.114103 -0.151040 -0.084189   
thalach  -0.398522 -0.044020  0.295762 -0.046698 -0.009940 -0.008567   
exang     0.096801  0.141664 -0.394280  0.067616  0.067023  0.025665   
oldpeak   0.210013  0.096093 -0.149230  0.193216  0.053952  0.005747   
slope    -0.168814 -0.030711  0.119717 -0.121475 -0.004038 -0.059894   
ca        0.276326  0.118261 -0.181053  0.101389  0.070511  0.137979   
thal      0.068001  0.210041 -0.161736  0.062210  0.098803 -0.032019   
target   -0.225439 -0.280937  0.433798 -0.144931 -0.085239 -0.028046   

           restecg   thalach     exang   oldpeak     slope        ca  \
age      -0.116211 -0.398522  0.096801  0.210013 -0.168814  0.276326   
sex      -0.058196 -0.044020  0.141664  0.096093 -0.030711  0.118261   
cp        0.044421  0.295762 -0.394280 -0.149230  0.119717 -0.181053   
trestbps -0.114103 -0.046698  0.067616  0.193216 -0.121475  0.101389   
chol     -0.151040 -0.009940  0.067023  0.053952 -0.004038  0.070511   
fbs      -0.084189 -0.008567  0.025665  0.005747 -0.059894  0.137979   
restecg   1.000000  0.044123 -0.070733 -0.058770  0.093045 -0.072042   
thalach   0.044123  1.000000 -0.378812 -0.344187  0.386784 -0.213177   
exang    -0.070733 -0.378812  1.000000  0.288223 -0.257748  0.115739   
oldpeak  -0.058770 -0.344187  0.288223  1.000000 -0.577537  0.222682   
slope     0.093045  0.386784 -0.257748 -0.577537  1.000000 -0.080155   
ca       -0.072042 -0.213177  0.115739  0.222682 -0.080155  1.000000   
thal     -0.011981 -0.096439  0.206754  0.210244 -0.104764  0.151832   
target    0.137230  0.421741 -0.436757 -0.430696  0.345877 -0.391724   

              thal    target  
age       0.068001 -0.225439  
sex       0.210041 -0.280937  
cp       -0.161736  0.433798  
trestbps  0.062210 -0.144931  
chol      0.098803 -0.085239  
fbs      -0.032019 -0.028046  
restecg  -0.011981  0.137230  
thalach  -0.096439  0.421741  
exang     0.206754 -0.436757  
oldpeak   0.210244 -0.430696  
slope    -0.104764  0.345877  
ca        0.151832 -0.391724  
thal      1.000000 -0.344029  
target   -0.344029  1.000000

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import chi2

fit_faetures =SelectKBest(score_func=f_classif)
fit_faetures.fit(x,y)


SelectKBest()

In [ ]:
fs= pd.DataFrame(fit_faetures.scores_,index=x.columns,columns =['score values'])
fs


score values
age          16.116700
sex          25.792191
cp           69.772271
trestbps      6.458169
chol          2.202983
fbs           0.236942
restecg       5.777209
thalach      65.120104
exang        70.952438
oldpeak      68.551439
slope        40.902071
ca           54.559834
thal         40.407696

In [ ]:
sp= fs.nlargest(9,'score values')
sp

score values
exang       70.952438
cp          69.772271
oldpeak     68.551439
thalach     65.120104
ca          54.559834
slope       40.902071
thal        40.407696
sex         25.792191
age         16.116700

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sb

# Check if the 'District' column exists
if 'District' in df.columns:
    # Create a mapping for districts to numerical values
    district_mapping = {district: i for i, district in enumerate(df['District'].unique())}

    # Map the district names to their corresponding numerical values
    df['District_encoded'] = df['District'].map(district_mapping)

    # Drop the original 'District' column
    df = df.drop('District', axis=1)
else:
    print("Warning: 'District' column not found in DataFrame. Skipping encoding.")

# Set up the figure size
plt.figure(1, figsize=(20, 10))  # Adjusted size for better visibility

# Select numerical columns for correlation
numerical_df = df.select_dtypes(include=['number'])

# Create the heatmap with a different color palette
sb.heatmap(numerical_df.corr(), annot=True, cmap='viridis')  # Change 'viridis' to your desired color code

# Add title
plt.title('Heatmap for the Data')
plt.show()
