<a href="https://colab.research.google.com/github/sajjadjim/Data-Minning-And-Machine-Learning/blob/main/Week2_(05_09_2024).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Dataset Data Mining /Dataset/iris.csv")

#show Data set
print(df)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.4           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.3          0.2     setosa
4             5.1          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]
First 10 rows:
   s

In [ ]:
# Print the first 10 rows
print("First 10 rows:")
print(df.head(10))

In [ ]:

# Print the last 10 rows
print("\nLast 10 rows:")
print(df.tail(10))


Last 10 rows:
     sepal_length  sepal_width  petal_length  petal_width    species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica


In [ ]:
#Deatils Description Print
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [ ]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [ ]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df.loc[3]

sepal_length       4.6
sepal_width        3.1
petal_length       1.3
petal_width        0.2
species         setosa
Name: 3, dtype: object

In [ ]:
#Show 0-4 row value
df.loc[0:4]

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.4           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.3          0.2  setosa
4           5.1          3.6           1.4          0.2  setosa

Differance Between loc and iloc

1.loc lebel Base
1.iloc index base

2.loc inclusive
2.iloc exclusive base



In [ ]:
df.iloc[0:4]

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.4           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.3          0.2  setosa

In [ ]:
#Specific 0-4 multiple_colums value

df.loc[0:4,['sepal_length','petal_length']]

sepal_length  petal_length
0           5.1           1.4
1           4.9           1.4
2           4.7           1.3
3           4.6           1.3
4           5.1           1.4

In [ ]:
#ilock is index base

df.iloc[0:4,0:3]

sepal_length  sepal_width  petal_length
0           5.1          3.5           1.4
1           4.9          3.4           1.4
2           4.7          3.2           1.3
3           4.6          3.1           1.3

In [ ]:
#Find the unique Value from giving dataset
pd.unique(df['sepal_length'])

array([5.1, 4.9, 4.7, 4.6, 5.4, 5. , 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

Find out unique value with sepal with before 7 index (Lab wok )

In [ ]:
# Solve problem
pd.unique(df.loc[0:6,'sepal_width'])

array([3.5, 3.4, 3.2, 3.1, 3.6, 3.9])

In [ ]:
#Solve Problem with iloc
pd.unique(df.iloc[0:7,1])

array([3.5, 3.4, 3.2, 3.1, 3.6, 3.9])

In [ ]:
#Dataset all float value concider and unique value print
df.select_dtypes(include='float64')

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.4           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.3          0.2
4             5.1          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]